swagger: "2.0"
info:
  version: "1.0.0"
  title: "Catalog"
host: "localhost:600"
basePath: "/api"

tags:
- name: "category"
  description: "Categories"
- name: "product"
  description: "Products"
schemes:
- "http"

paths:
  "/categories":
    get:
      tags:
      - "category"
      summary: "Returns category collection"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
    post:
      tags:
      - "category"
      summary: "Creates one"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Category"
      security:
      - grantTypePassword: []
      responses:
        405:
          description: "Invalid input"
  "/categories/{categoryId}":
    put:
      tags:
      - "category"
      summary: "Update existing"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "categoryId"
        description: "Category id"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Category"
      security:
      - grantTypePassword: []
      responses:
        405:
          description: "Invalid input"
    delete:
      tags:
      - "category"
      summary: "Delete"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "categoryId"
        description: "Category id"
        required: true
        type: "integer"
      security:
      - grantTypePassword: []
      responses:
        405:
          description: "Invalid input"
  "/categories/{categoryId}/products":
    get:
      tags:
      - "category"
      summary: "Get product collection in specific category"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "categoryId"
        description: "Category id"
        required: true
        type: "integer"
      responses:
        405:
          description: "Invalid input"
  "/products":
    post:
      tags:
      - "product"
      summary: "Creates one"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Product"
      security:
      - grantTypePassword: []
      responses:
        405:
          description: "Invalid input"
  "/products/{productId}":
    put:
      tags:
      - "product"
      summary: "Update existing"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "productId"
        description: "Product id"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Product"
      security:
      - grantTypePassword: []
      responses:
        405:
          description: "Invalid input"
    delete:
      tags:
      - "product"
      summary: "Delete"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "productId"
        description: "Product id"
        required: true
        type: "integer"
      security:
      - grantTypePassword: []
      responses:
        405:
          description: "Invalid input"
  "/products/{productId}/sell":
    get:
      tags:
      - "product"
      summary: "Sell product (decrease amount by 1)"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "productId"
        description: "Product id"
        required: true
        type: "integer"
      responses:
        405:
          description: "Invalid input"
  "/products/{productId}/return":
    get:
      tags:
      - "product"
      summary: "Sell product (increase amount by 1)"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "productId"
        description: "Product id"
        required: true
        type: "integer"
      responses:
        405:
          description: "Invalid input"
definitions:
  Category:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      name:
        type: "string"
        example: "Shirts"
  Product:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      name:
        type: "string"
        example: "Shirt Nike test XL"
      amount:
        type: "integer"
        format: "int64"
securityDefinitions:
  grantTypePassword:
    type: oauth2
    scopes:
    flow: password
    tokenUrl: http://localhost:600/oauth/token